import React, { useState, useEffect } from 'react';
import { DataTable } from '@/components/ui/data-table';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { toast } from 'sonner';
import { api } from '@/services/api';

export interface User {
  id: string;
  username: string;
  email: string;
  role: 'user' | 'admin';
  isActive: boolean;
  balance: number;
  createdAt: string;
  updatedAt?: string;
}

const Users = () => {
  const [users, setUsers] = useState<User[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [newUser, setNewUser] = useState({
    username: '',
    email: '',
    password: '',
    role: 'user',
    isActive: true,
    balance: 0,
  });

  useEffect(() => {
    fetchUsers();
  }, []);

  const fetchUsers = async () => {
    setIsLoading(true);
    try {
      const data = await api.getAllUsers();
      setUsers(data);
    } catch (error) {
      console.error('Failed to fetch users', error);
      toast.error('فشل في جلب قائمة المستخدمين');
    } finally {
      setIsLoading(false);
    }
  };

  const handleAddUser = async () => {
    if (!newUser.username || !newUser.password || !newUser.email) {
      toast.error('يرجى ملء جميع الحقول المطلوبة');
      return;
    }

    try {
      // Remove createdAt from newUser since it's generated by the backend
      const userToAdd = {
        username: newUser.username,
        email: newUser.email,
        password: newUser.password,
        role: newUser.role,
        isActive: newUser.isActive,
        balance: newUser.balance || 0,
      };
      
      const addedUser = await api.createUser(userToAdd);
      setUsers([...users, addedUser]);
      setNewUser({
        username: '',
        email: '',
        password: '',
        role: 'user',
        isActive: true,
        balance: 0,
      });
      setDialogOpen(false);
      toast.success(`تم إضافة المستخدم ${addedUser.username} بنجاح`);
    } catch (error) {
      console.error('Failed to add user', error);
      toast.error('فشل في إضافة المستخدم');
    }
  };

  const handleUpdateUser = async (id: string, data: Partial<User>) => {
    try {
      const updatedUser = await api.updateUser(id, data);
      setUsers(users.map(user => user.id === id ? updatedUser : user));
      toast.success('تم تحديث بيانات المستخدم بنجاح');
    } catch (error) {
      console.error('Failed to update user', error);
      toast.error('فشل في تحديث بيانات المستخدم');
    }
  };

  const handleDeleteUser = async (id: string) => {
    if (!window.confirm('هل أنت متأكد من رغبتك في حذف هذا المستخدم؟')) return;
    
    try {
      await api.deleteUser(id);
      setUsers(users.filter(user => user.id !== id));
      toast.success('تم حذف المستخدم بنجاح');
    } catch (error) {
      console.error('Failed to delete user', error);
      toast.error('فشل في حذف المستخدم');
    }
  };

  const columns = [
    {
      accessorKey: 'username',
      header: 'اسم المستخدم',
    },
    {
      accessorKey: 'email',
      header: 'البريد الإلكتروني',
    },
    {
      accessorKey: 'role',
      header: 'الدور',
    },
    {
      accessorKey: 'balance',
      header: 'الرصيد',
    },
    {
      accessorKey: 'isActive',
      header: 'نشط',
      cell: ({ row }) => (
        <Switch 
          checked={row.original.isActive} 
          onCheckedChange={(checked) => 
            handleUpdateUser(row.original.id, { isActive: checked })
          }
        />
      )
    },
    {
      id: 'actions',
      header: 'الإجراءات',
      cell: ({ row }) => (
        <Button 
          variant="destructive" 
          size="sm"
          onClick={() => handleDeleteUser(row.original.id)}
        >
          حذف
        </Button>
      )
    }
  ];

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold">إدارة المستخدمين</h1>
        <Button onClick={() => setDialogOpen(true)}>إضافة مستخدم جديد</Button>
      </div>
      
      <Card className="overflow-hidden">
        <DataTable 
          columns={columns} 
          data={users} 
          loading={isLoading} 
          onRefresh={fetchUsers}
        />
      </Card>

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>إضافة مستخدم جديد</DialogTitle>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="username">اسم المستخدم</Label>
              <Input 
                id="username"
                value={newUser.username}
                onChange={(e) => setNewUser({...newUser, username: e.target.value})}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">البريد الإلكتروني</Label>
              <Input 
                id="email"
                type="email"
                value={newUser.email}
                onChange={(e) => setNewUser({...newUser, email: e.target.value})}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">كلمة المرور</Label>
              <Input 
                id="password"
                type="password"
                value={newUser.password}
                onChange={(e) => setNewUser({...newUser, password: e.target.value})}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="role">الدور</Label>
              <Select onValueChange={(value) => setNewUser({...newUser, role: value as 'user' | 'admin'})}>
                <SelectTrigger className="w-[180px]">
                  <SelectValue placeholder="اختر دور المستخدم" defaultValue={newUser.role} />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="user">مستخدم</SelectItem>
                  <SelectItem value="admin">مدير</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="flex items-center space-x-2">
              <Switch 
                id="isActive"
                checked={newUser.isActive}
                onCheckedChange={(checked) => setNewUser({...newUser, isActive: checked})}
              />
              <Label htmlFor="isActive">نشط</Label>
            </div>
            <div className="space-y-2">
              <Label htmlFor="balance">الرصيد</Label>
              <Input
                id="balance"
                type="number"
                value={newUser.balance?.toString()}
                onChange={(e) => setNewUser({ ...newUser, balance: parseFloat(e.target.value) || 0 })}
              />
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setDialogOpen(false)}>إلغاء</Button>
            <Button onClick={handleAddUser}>إضافة</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default Users;
